name: 'Release and publish Workflow'

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create release'
        required: true
        type: boolean
        default: 'true'
      publish_packages:
        description: 'Publish npm packages'
        required: true
        type: boolean
        default: 'true'
  push:
    branches: [main]

jobs:

  # A separate release build that is only run for commits that are the result of merging the "Version Packages" PR
  # We can't re-use the output from the above step, but we'll have a guaranteed node_modules cache and
  # only run the build steps that are necessary for publishing
  release:

    if: needs.build.outputs.needs_release == 'true' || github.event.inputs.create_release || github.event.inputs.publish_packages

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      CI: 'true'
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Prepare .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          # next lines prevents [lerna ERR! EUNCOMMIT  M .npmrc] during publish
          git config --global user.email "nobody@oriflame.com"
          git config --global user.name "nobody"
          git add .npmrc
          git commit -m "unnecessary commit"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install --frozen-lockfile
        uses: backstage/actions/yarn-install@v0.5.13
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: build type declarations
        run: yarn tsc:full

      - name: build packages
        run: yarn backstage-cli repo build

      # Publishes current version of packages that are not already present in the registry
      - name: publish
        if: needs.build.outputs.needs_release == 'true' || github.event.inputs.publish_packages
        run: |
          if [ -f ".changeset/pre.json" ]; then
              yarn lerna -- publish from-package --yes --dist-tag next
          else
              yarn lerna -- publish from-package --yes
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Grabs the version in the root package.json and creates a tag on GitHub
      - name: Create a release tag
        id: create_tag
        if: needs.build.outputs.needs_release == 'true' || github.event.inputs.create_release
        run: node scripts/create-release-tag.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Convert the newly created tag into a release with changelog information
      - name: Create release on GitHub
        if: needs.build.outputs.needs_release == 'true' || github.event.inputs.create_release
        run: node scripts/create-github-release.js ${{ steps.create_tag.outputs.tag_name }} 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
